import Foundation

let cancelled = AirPlayAttempt(name: "Room TV")
cancelled.cancel()
assert(cancelled.isCancelled && !cancelled.beginRequest())
assert(!cancelled.ownsConnection)
let first = AirPlayAttempt(name: "Room TV")
assert(first.beginRequest() && first.ownsConnection)
first.cancel()
assert(first.ownsConnection, "Cancellation must retain ownership for rollback")
let retry = AirPlayAttempt(name: "Room TV")
assert(first.id != retry.id && first !== retry)
assert(!retry.isCancelled && retry.beginRequest(), "An old cancellation must not cancel the retry")
assert(first.deadline > Date())
assert(retry.matches(receiver: AirPlayAttempt.receiver(in: "Room TV (AirPlay)")))
assert(!retry.matches(receiver: AirPlayAttempt.receiver(in: "iPad (Sidecar)")))
assert(!retry.matches(receiver: AirPlayAttempt.receiver(in: "Other TV (AirPlay)")))
assert(!retry.matches(receiver: nil))
assert(AirPlayAttempt.receiver(in: "Room TV") == nil)
let group = DispatchGroup()
let concurrent = AirPlayAttempt(name: "Race TV")
for _ in 0..<100 {
    DispatchQueue.global().async(group: group) { concurrent.cancel(); _ = concurrent.beginRequest() }
}
group.wait()
assert(concurrent.isCancelled && !concurrent.beginRequest())
print("PASS: production request identity, cancellation/rollback ownership, exact receiver matching, and concurrent cancellation")

let late = AirPlayAttempt(name: "Late TV")
_ = late.beginRequest(); late.cancel()
assert(!late.canRelease(receiverPresent: false, quiet: true, now: late.deadline.addingTimeInterval(-1)))
assert(late.canRelease(receiverPresent: false, quiet: true, now: late.deadline.addingTimeInterval(1)))
assert(!late.canRelease(receiverPresent: true, quiet: true, now: late.deadline.addingTimeInterval(1)))
assert(!late.canRelease(receiverPresent: false, quiet: false, now: late.deadline.addingTimeInterval(1)))
assert(late.needsLateConnectionWatch)
late.markConnected()
assert(!late.needsLateConnectionWatch)
assert(late.canRelease(receiverPresent: false, quiet: true, now: late.deadline.addingTimeInterval(-1)))
print("PASS: pending cancellation waits for deadline; connected sessions require quiet absence")
